#!/bin/bash

START=$SECONDS

$@

STATUS="$(echo $?)"
NAME="$(echo $@)"

case $STATUS in 
    0) MSG='Success';;
    1) MSG='Operation not permitted';;
    2) MSG='No such file or directory';;
    3) MSG='No such process';;
    4) MSG='Interrupted system call';;
    5) MSG='Input/output error';;
    6) MSG='No such device or address';;
    7) MSG='Argument list too long';;
    8) MSG='Exec format error';;
    9) MSG='Bad file descriptor';;
    10) MSG='No child processes';;
    11) MSG='Resource temporarily unavailable';;
    12) MSG='Cannot allocate memory';;
    13) MSG='Permission denied';;
    14) MSG='Bad address';;
    15) MSG='Block device required';;
    16) MSG='Device or resource busy';;
    17) MSG='File exists';;
    18) MSG='Invalid cross-device link';;
    19) MSG='No such device';;
    20) MSG='Not a directory';;
    21) MSG='Is a directory';;
    22) MSG='Invalid argument';;
    23) MSG='Too many open files in system';;
    24) MSG='Too many open files';;
    25) MSG='Inappropriate ioctl for device';;
    26) MSG='Text file busy';;
    27) MSG='File too large';;
    28) MSG='No space left on device';;
    29) MSG='Illegal seek';;
    30) MSG='Read-only file system';;
    31) MSG='Too many links';;
    32) MSG='Broken pipe';;
    33) MSG='Numerical argument out of domain';;
    34) MSG='Numerical result out of range';;
    35) MSG='Resource deadlock avoided';;
    36) MSG='File name too long';;
    37) MSG='No locks available';;
    38) MSG='Function not implemented';;
    39) MSG='Directory not empty';;
    40) MSG='Too many levels of symbolic links';;
    42) MSG='No message of desired type';;
    43) MSG='Identifier removed';;
    44) MSG='Channel number out of range';;
    45) MSG='Level 2 not synchronized';;
    46) MSG='Level 3 halted';;
    47) MSG='Level 3 reset';;
    48) MSG='Link number out of range';;
    49) MSG='Protocol driver not attached';;
    50) MSG='No CSI structure available';;
    51) MSG='Level 2 halted';;
    52) MSG='Invalid exchange';;
    53) MSG='Invalid request descriptor';;
    54) MSG='Exchange full';;
    55) MSG='No anode';;
    56) MSG='Invalid request code';;
    57) MSG='Invalid slot';;
    59) MSG='Bad font file format';;
    60) MSG='Device not a stream';;
    61) MSG='No data available';;
    62) MSG='Timer expired';;
    63) MSG='Out of streams resources';;
    64) MSG='Machine is not on the network';;
    65) MSG='Package not installed';;
    66) MSG='Object is remote';;
    67) MSG='Link has been severed';;
    68) MSG='Advertise error';;
    69) MSG='Srmount error';;
    70) MSG='Communication error on send';;
    71) MSG='Protocol error';;
    72) MSG='Multihop attempted';;
    73) MSG='RFS specific error';;
    74) MSG='Bad message';;
    75) MSG='Value too large for defined data type';;
    76) MSG='Name not unique on network';;
    77) MSG='File descriptor in bad state';;
    78) MSG='Remote address changed';;
    79) MSG='Can not access a needed shared library';;
    80) MSG='Accessing a corrupted shared library';;
    81) MSG='.lib section in a.out corrupted';;
    82) MSG='Attempting to link in too many shared libraries';;
    83) MSG='Cannot exec a shared library directly';;
    84) MSG='Invalid or incomplete multibyte or wide character';;
    85) MSG='Interrupted system call should be restarted';;
    86) MSG='Streams pipe error';;
    87) MSG='Too many users';;
    88) MSG='Socket operation on non-socket';;
    89) MSG='Destination address required';;
    90) MSG='Message too long';;
    91) MSG='Protocol wrong type for socket';;
    92) MSG='Protocol not available';;
    93) MSG='Protocol not supported';;
    94) MSG='Socket type not supported';;
    95) MSG='Operation not supported';;
    96) MSG='Protocol family not supported';;
    97) MSG='Address family not supported by protocol';;
    98) MSG='Address already in use';;
    99) MSG='Cannot assign requested address';;
    100) MSG='Network is down';;
    101) MSG='Network is unreachable';;
    102) MSG='Network dropped connection on reset';;
    103) MSG='Software caused connection abort';;
    104) MSG='Connection reset by peer';;
    105) MSG='No buffer space available';;
    106) MSG='Transport endpoint is already connected';;
    107) MSG='Transport endpoint is not connected';;
    108) MSG='Cannot send after transport endpoint shutdown';;
    109) MSG='Too many references';;
    110) MSG='Connection timed out';;
    111) MSG='Connection refused';;
    112) MSG='Host is down';;
    113) MSG='No route to host';;
    114) MSG='Operation already in progress';;
    115) MSG='Operation now in progress';;
    116) MSG='Stale file handle';;
    117) MSG='Structure needs cleaning';;
    118) MSG='Not a XENIX named type file';;
    119) MSG='No XENIX semaphores available';;
    120) MSG='Is a named type file';;
    121) MSG='Remote I/O error';;
    122) MSG='Disk quota exceeded';;
    123) MSG='No medium found';;
    125) MSG='Operation canceled';;
    126) MSG='Required key not available';;
    127) MSG='Key has expired';;
    128) MSG='Key has been revoked';;
    129) MSG='Key was rejected by service';;
    130) MSG='Owner died';;
    131) MSG='State not recoverable';;
    132) MSG='Operation not possible due to RF-kill';;
    133) MSG='Memory page has hardware error';;
    *) MSG="Unknown error";;
esac

TIME=$(date -ud "@$(( $SECONDS - $START ))" "+%H:%M:%S")

ssh -p22222 quizznor@localhost notify-send -a SSH "'$NAME' 'returned $STATUS ($MSG)'"
echo $NAME -- return $STATUS -- after $TIME
